service: chase-rewards
provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: nodejs20.x
  environment:
    LOG_LEVEL: info
  iam:
    role:
      name: chase-rewards-role
      statements:
        - Effect: "Allow"
          Resource:
            - "Fn::Join":
                - ":"
                - - "arn:aws:dynamodb"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - "table/chase-rewards-past-offers"
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
        - Effect: "Allow"
          Resource:
            - "Fn::Join":
                - ":"
                - - "arn:aws:secretsmanager"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - "secret"
                  - "chase-rewards-secrets*"
          Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
package:
  individually: true
  patterns:
    - "src/**"
    - "!src/__tests__/**"
    - "!node_modules/@aws-sdk/**" # The Lambda execution environment provides @aws-sdk/* builtin, so exclude it from packaging.
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
functions:
  main:
    memorySize: 128
    handler: src/main.default
    events:
      - schedule: cron(0 13 * * ? *)
custom:
  esbuild:
    bundle: true
    minify: true
    keepNames: true
    packager: yarn
    target: node20
    exclude:
      - "@aws-sdk/*"
resources:
  Resources:
    PastOffersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: chase-rewards-past-offers
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    ChaseRewardsSecrets:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: chase-rewards-secrets
